# Use root/example as user/password credentials

version: '3.8'

services:

  adminer:
    container_name: agilicious-adminer
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080

  db:
    container_name: agilicious-db
    image: postgres:12.3-alpine
    restart: always
    environment:
      POSTGRES_USER: agilicious
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  wiremock:
    container_name: agilicious-wiremock
    image: rodolpheche/wiremock
    restart: always
    ports:
      - 8443:8443
    volumes:
      - ../wiremock:/home/wiremock
    command:
      - --https-port
      - "8443"
      - --verbose
      # - --proxy-all=https://agilicious.atlassian.net
      # - --record-mappings
