---
on:
  pull_request:
    types:
      - labeled
      - opened
      - closed
      - reopened
jobs:
  add-labels:
    if: github.event.action != 'closed' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Add labels
    steps:
      - uses: actions/checkout@v2
      - uses: IvanFon/super-labeler-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
